# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CeMwa-BYzah5E-Knjo7Pxk7dB7Nd6oqk
"""

!pip install scikit-learn pandas

# movie_recommendation.py
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity

# --- Sample dataset ---
movies = pd.DataFrame({
    'user': ['A', 'A', 'A', 'B', 'B', 'C', 'C', 'D'],
    'movie': ['Inception', 'Interstellar', 'Memento', 'Inception', 'Tenet', 'Memento', 'Interstellar', 'Tenet'],
    'rating': [5, 4, 4, 5, 4, 5, 3, 2]
})

# --- Create pivot table ---
pivot = movies.pivot_table(index='user', columns='movie', values='rating').fillna(0)

# --- Compute similarity ---
similarity = cosine_similarity(pivot)
similarity_df = pd.DataFrame(similarity, index=pivot.index, columns=pivot.index)

# --- Simple recommender ---
def recommend(user):
    similar_users = similarity_df[user].sort_values(ascending=False)
    target_user_movies = set(movies[movies['user']==user]['movie'])
    recommendations = []
    for similar_user in similar_users.index[1:]:
        user_movies = movies[movies['user']==similar_user]
        for _, row in user_movies.iterrows():
            if row['movie'] not in target_user_movies and row['rating']>=4:
                recommendations.append(row['movie'])
    return list(set(recommendations))

print("Movies recommended for user A:", recommend('A'))

